/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.sql.*;

import org.example.database_utils.Database;
import org.example.database_utils.DatabaseInterface;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws SQLException {
        DatabaseInterface databaseInterface = new Database();

        databaseInterface.testDatabaseConnection();

        databaseInterface.cleanup();

        System.out.println(new App().getGreeting());
    }
}
