/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.sql.*;

import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {
    // private int counter = 0;

    private int windowWidth = 640;
    private int windowHeight = 480;

    private Navigator navigator;

    public String getGreeting() {
        return "Hello World!";
    }

    @Override
    public void start(Stage stage) {
        this.navigator = new Navigator(stage, this.windowWidth, this.windowHeight);
        this.navigator.setTitle("Hello World!");
        this.navigator.startNavigator();
    }

    public static void main(String[] args) throws SQLException {
        DatabaseInterface databaseInterface = new Database();

        databaseInterface.testDatabaseConnection();

        databaseInterface.cleanup();

        System.out.println(new App().getGreeting());

        launch();
    }
}
